name: Build

on:
  push:
    tags:
    - '*'
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: 
      contents: read
      packages: write 

    env:
      JEOMETRY_REPO: 'jeometry-org/jeometry'
      REVOLSYS_REPO: 'revolsys/com.revolsys.open'

    steps:

#### Checkout jeometry ####
    - name: Checkout jeometry
      uses: actions/checkout@v4
      with:
        ref: ${{env.OTHER_REF}}
        repository: ${{env.JEOMETRY_REPO}}
        path: jeometry
        token: ${{secrets.PUSH_TOKEN}}

#### Checkout revolsys ####
    - name: Checkout revolsys
      uses: actions/checkout@v4
      with:
        ref: ${{env.REF}}
        repository: ${{github.repository}}
        path: revolsys

#### JAVA VERSION ####
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: 'maven'

#### Initialize Environment ####
    - name: Initialize Environment
      run: |
        REF="$GITHUB_REF"
        if [[ "$REF" =~ ^refs/heads/.* ]]; then
          REF="${REF/refs\/heads\//}"
          OTHER_REF=${REF}
        elif [[ "$REF" =~ ^refs/tags/.* ]]; then
          REF="${REF/refs\/tags\//}"
          OTHER_REF=0.REVOLSYS-${REF}
        else
          echo "Ref must be a branch or tag '${REF}'"
          exit -1
        fi
        echo "REF=${REF}" >> $GITHUB_ENV
        echo "OTHER_REF=${OTHER_REF}" >> $GITHUB_ENV

#### Get App Version ####
    - name: Get Project Version
      working-directory: ./revolsys
      run: echo "PROJECT_VERSION=$(grep version pom.xml|head -1 | sed 's/<\/*version>//g' | sed 's/ //g')" >> $GITHUB_ENV

#### Set Snapshot Version ####
    - name: Set Snapshot Version
      if: contains(env.PROJECT_VERSION, 'SNAPSHOT')
      run: |
        BASE_REF=$(echo "$REF" | tr '[:lower:]' '[:upper:]')
        OTHER_VERSION="0.REVOLSYS-${BASE_REF}-SNAPSHOT"
        VERSION="${BASE_REF}-SNAPSHOT"
        find jeometry -name pom.xml -exec sed -i "s/<version>.*-SNAPSHOT<\\/version>/<version>${OTHER_VERSION}<\\/version>/g" {} \;    
        sed -i "s/<org.jeometry.version>.*<\\/org.jeometry.version>/<org.jeometry.version>${OTHER_VERSION}<\\/org.jeometry.version>/g" ./revolsys/pom.xml
        
#### Build ####
    - name: Build
      working-directory: ./revolsys
      run: mvn -B -ntp -DskipTests -Dmaven.javadoc.skip=true -Dmaven.source.skip install
