name: Build

on:

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: 
      contents: read
      packages: write 

    env:
      JEOMETRY_REPO: 'jeometry-org/jeometry'
      REVOLSYS_REPO: 'revolsys/com.revolsys.open'

    steps:

#### JAVA VERSION ####
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'microsoft'

#### Initialize Environment ####
    - name: Initialize Environment
      run: |
        BRANCH=${GITHUB_REF#refs/heads/}

        TAG="${{github.event.inputs.tag}}"
        if [[ -z "$TAG" ]]; then
          if [[ "$GITHUB_REF" =~ ^refs/tags/.* ]]; then
            TAG="${GITHUB_REF/refs\/tags\//}"
          fi
        fi
        
        if [[ ! -z "$TAG" ]]; then
          REF=${TAG}
          OTHER_REF=0.REVOLSYS-${TAG}
        else
          REF=${BRANCH}
          OTHER_REF=$REF
        fi
        echo "REF=${REF}" >> $GITHUB_ENV
        echo "OTHER_REF=${OTHER_REF}" >> $GITHUB_ENV

#### Checkout jeometry ####
    - name: Checkout jeometry
      uses: actions/checkout@v2
      with:
        ref: ${{env.OTHER_REF}}
        repository: ${{env.JEOMETRY_REPO}}
        path: jeometry
        token: ${{secrets.PUSH_TOKEN}}

#### Checkout revolsys ####
    - name: Checkout revolsys
      uses: actions/checkout@v2
      with:
        ref: ${{env.REF}}
        repository: ${{github.repository}}
        path: revolsys

#### MAVEN REPOSITORY CACHE ####
    - uses: actions/cache@v2
      with:
        path: |
          '~/.m2/repository'
          '!~/.m2/repository/org/jeometry'
          '!~/.m2/repository/com/revolsys/open'
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

#### Get App Version ####
    - name: Get Project Version
      working-directory: ./revolsys
      run: echo "PROJECT_VERSION=$(grep version pom.xml|head -1 | sed 's/<\/*version>//g' | sed 's/ //g')" >> $GITHUB_ENV

#### Set Snapshot Version ####
    - name: Set Snapshot Version
      if: contains(env.PROJECT_VERSION, 'SNAPSHOT')
      run: |
        BASE_REF=$(echo "$REF" | tr '[:lower:]' '[:upper:]')
        OTHER_VERSION="0.REVOLSYS-${BASE_REF}-SNAPSHOT"
        VERSION="${BASE_REF}-SNAPSHOT"
        sed -i "s/<org.jeometry.version>.*<\\/org.jeometry.version>/<org.jeometry.version>${OTHER_VERSION}<\\/org.jeometry.version>/g" ./revolsys/pom.xml
        mvn -f ./jeometry/pom.xml -B -q versions:set "-DnewVersion=${OTHER_VERSION}" -DgenerateBackupPoms=false -DprocessDependencies=false
        
#### Build ####
    - name: Build
      working-directory: ./revolsys
      run: mvn -B -ntp install -DskipTests
